Repository qbentil/bentility, pull requests merged in 2022-09, with the labels that each got.

#22 Full update on data fetch > fix on session
  components/Admin/categories/index.tsx
  components/Admin/categories/unit.tsx
  context/initialState.js
  context/reducer.js
  pages/_app.tsx
  pages/admin/auth/LoginForm.tsx
  pages/admin/index.tsx
  types.tsx
  util/index.tsx
  util/session.tsx
Labels: enhancement, good first issue, Bug Fix

#27 Qbentil: Complete add category with backend
  admin/categories/new/index.tsx
  components/Admin/sidenav/index.tsx
  components/Button/Button.tsx
  components/Button/index.tsx
  components/Preloader/index.tsx
  firebase.config.js
  firebase/index.ts
  package-lock.json
  package.json
  types.tsx
  util/categories.tsx
Labels: feature

#29 Fixed image control
  admin/categories/new/index.tsx
  components/Admin/categories/index.tsx
  components/Admin/categories/unit.tsx
  package-lock.json
Labels: Bug Fix

#36 Resolve issue #35
  components/Admin/new/editor.tsx
  components/Admin/new/index.tsx
  components/Button/index.tsx
  types.tsx
Labels: Bug Fix

#37 Qbentil: Connect Add Post with API
  admin/categories/new/index.tsx
  components/Admin/categories/index.tsx
  components/Admin/categories/tableunit.tsx
  components/Admin/categories/unit.tsx
  components/Admin/new/index.tsx
  components/UtilButton/index.tsx
  components/Validations/index.ts
  components/Validations/index.tsx
  styles/globals.css
  types.tsx
  util/categories.tsx
  util/posts.ts
Labels: enhancement

#43 Qbentil: I'm tired of Naming PR's😤😤😤
  components/Admin/navbar/index.tsx
  components/Admin/posts/index.tsx
  components/Admin/sidenav/index.tsx
  components/UtilButton/index.tsx
  context/initialState.js
  context/reducer.js
  util/admins.ts
  util/functions.ts
Labels: enhancement

#49 Qbentil: Complete Dashboard home
  components/Admin/Tabs/index.tsx
  components/Admin/popular-categories/unit.tsx
  components/Admin/post/index.tsx
  components/Admin/posts/index.tsx
  pages/admin/auth/LoginForm.tsx
  util/functions.ts
Labels: feature

#52 Qbentil: Create User
  admin/users/new/index.tsx
  components/Admin/categories/tableunit.tsx
  components/Admin/categories/unit.tsx
  components/Admin/new/index.tsx
  components/Admin/users/index.tsx
  components/Selectors/categorySelector.tsx
  components/Selectors/usertype.tsx
  context/reducer.js
  pages/admin/users/new/index.tsx
  types.tsx
  util/admins.ts
Labels: feature

#53 Update Popular posts to fit categories
  components/Admin/post/index.tsx
Labels: good first issue

#55 Qbentil: Protect Admin Routes
  components/Admin/sidenav/index.tsx
  pages/admin/index.tsx
Labels: feature

#58 Qbentil: Setup Settings Page
  admin/new/index.tsx
  admin/settings/index.tsx
  components/Admin/Tabs/index.tsx
  components/Admin/navbar/index.tsx
  components/Admin/users/index.tsx
  components/ImageUploader/imageBox.tsx
  components/ImageUploader/uploader.tsx
  components/settings/App/Profile.tsx
  components/settings/App/index.tsx
  components/settings/App/platform.tsx
  components/settings/editbox.tsx
  components/settings/header.tsx
  components/settings/index.tsx
  components/settings/security.tsx
  components/settings/update.tsx
  context/reducer.js
  util/admins.ts
Labels: enhancement, feature

#59 Remove buggy update avatar functions
  components/settings/update.tsx
Labels: good first issue

#60 Qbentil: Complete User settings
  components/settings/editbox.tsx
  components/settings/security.tsx
  components/settings/update.tsx
  context/reducer.js
  firebase/index.ts
  util/admins.ts
Labels: good first issue, feature

#61 UI touches accross app
  admin/categories/new/index.tsx
  admin/users/new/index.tsx
  components/Admin/categories/index.tsx
  components/Admin/categories/unit.tsx
  components/settings/editbox.tsx
  components/settings/security.tsx
  components/settings/update.tsx
Labels: enhancement, good first issue

#65 Qbentil: Implement search in all models
  admin/categories/edit.tsx
  admin/categories/view.tsx
  admin/categories/viewcategory.tsx
  admin/posts/edit.tsx
  admin/posts/view.tsx
  admin/posts/viewpost.tsx
  admin/users/index.tsx
  admin/users/user/App/Profile.tsx
  admin/users/user/App/index.tsx
  admin/users/user/App/platform.tsx
  admin/users/user/editbox.tsx
  admin/users/user/header.tsx
  admin/users/user/index.tsx
  admin/users/user/main.tsx
  admin/users/user/security.tsx
  admin/users/user/update.tsx
  components/Admin/Searchbar/index.tsx
  components/Admin/categories/index.tsx
  components/Admin/categories/tableunit.tsx
  components/Admin/categories/unit.tsx
  components/Admin/navbar/index.tsx
  components/Admin/posts/index.tsx
  components/Admin/sidenav/index.tsx
  components/Admin/users/index.tsx
  components/Promises/index.js
  components/Searchbar/index.tsx
  components/UtilButton/index.tsx
  pages/admin/index.tsx
  pages/admin/posts/index.tsx
  pages/admin/users/user/[username].tsx
  public/images/no-data.svg
  tsconfig.json
  types.tsx
Labels: feature

#69 Qbentil: COmplete Update category feat🎉🚀
  admin/categories/edit.tsx
  admin/categories/view.tsx
  context/reducer.js
  util/categories.tsx
Labels: enhancement, feature
